/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file CalculatorServerImpl.cxx
 * This source file contains the definition of the skeleton for interface Calculator. This definitions have to be implemented.
 *
 * This file was generated by the tool rpcddsgen.
 */
 
#include "CalculatorServerImpl.h"

 
CORBA::LongLong CalculatorServerImpl::addition(/*in*/ CORBA::Long x, /*in*/ CORBA::Long y) 
{
    CORBA::LongLong  addition_ret = 0;

    addition_ret = x + y;
   
    return addition_ret;
} 
 
CORBA::LongLong CalculatorServerImpl::substraction(/*in*/ CORBA::Long x, /*in*/ CORBA::Long y) 
{
    CORBA::LongLong  substraction_ret = 0;

    substraction_ret = x - y;
   
    return substraction_ret;
} 
 
CORBA::LongLong CalculatorServerImpl::multiplication(/*in*/ CORBA::Long x, /*in*/ CORBA::Long y) 
{
    CORBA::LongLong  multiplication_ret = 0;

    multiplication_ret = x * y;
   
    return multiplication_ret;
} 
 
CORBA::LongLong CalculatorServerImpl::division(/*in*/ CORBA::Long x, /*in*/ CORBA::Long y) 
{
    CORBA::LongLong  division_ret = 0;

    division_ret = x / y;
   
    return division_ret;
} 