/*************************************************************************
 * Copyright (c) 2012 eProsima. All rights reserved.
 *
 * This copy of RPCDDS is licensed to you under the terms described in the
 * RPCDDS_LICENSE file included in this distribution.
 *
 *************************************************************************
 * 
 * @file Client.cxx
 * This source file shows a simple example of how to create a proxy for interface Calculator.
 *
 * This file was generated by the tool rpcddsgen.
 */

#include "CalculatorProxy.h"
#include "CalculatorRequestReplyTypeSupportImpl.h"
#include "exceptions/Exceptions.h"

#include <iostream>

int main(int argc, char **argv)
{
    CalculatorProxy *proxy = NULL;
    
    // Creation of the proxy for interface "Calculator".
    try
    {
        proxy = new CalculatorProxy("RTICalculatorService");
    }
    catch(eProsima::RPCDDS::InitializeException &ex)
    {
        std::cout << ex.what() << std::endl;
        return -1;
    }

    // Create and initialize parameters.
    CORBA::Long  x = 5;
    CORBA::Long  y = 6;


    // Create and initialize return value.
    CORBA::Long  addition_ret = 0;

    // Call to remote procedure "addition".
    try
    {
        addition_ret = proxy->addition(x, y);
        std::cout << "ret = " << addition_ret << std::endl;
    }
    catch(eProsima::RPCDDS::Exception &ex)
    {
        std::cout << ex.what() << std::endl;
    }




    
    delete(proxy);
   
    return 0;
}